---
helmDefaults:
  tillerless: true
  wait: false
releases:
  - name: {{ requiredEnv "ENV" }}-mongodb
    namespace: {{ requiredEnv "NS" }}
    chart: ./charts
    values:
    - ./values/{{ requiredEnv "ENV" }}/values.yaml
