{{- if .Values.additionalUsers }}
{{- if gt (len .Values.additionalUsers) 0}}
{{ $projectName := (.Values.opsManager.projectName | lower) }}
{{ $clusterName := .Values.clusterName }}
{{ range .Values.additionalUsers }}
---
apiVersion: mongodb.com/v1
kind: MongoDBUser
metadata:
  name: "{{ $projectName }}-{{ .username | lower }}"
spec:
  passwordSecretKeyRef:
    name: {{ .passwdSecret }}
    key: password
  username: {{ .username }} 
  db: "admin"
  mongodbResourceRef:
    name: {{ $clusterName | lower | quote }}
  roles:
  {{- range .roles }}
    - db: {{ .db }}
      name: {{ .role }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}