{{- include "mongodb-deployment.validate" . -}}
{{- $sharded := and (hasKey .Values "sharding") (eq ((.Values.sharding | default dict).enabled | default false) true) -}}
---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: {{ .Values.clusterName | lower }}
  annotations:
    mongodb.com/v1.architecture: {{ ternary "static" "non-static" (ne (.Values.staticPods | toString) "false") | quote }}
spec:
  version: {{ .Values.mongoDBVersion | quote }}
  {{- if (hasKey .Values "mongoDBFCV") }}
  {{- if and (kindIs "string" .Values.mongoDBFCV) (regexMatch "^\\d\\.\\d$" .Values.mongoDBFCV) }}
  featureCompatibilityVersion: {{ .Values.mongoDBFCV | quote }}
  {{- else }}
  {{- fail "mongoDBFCV must be a string in the format of \"x.x\", such as \"6.0\"" }}
  {{- end }}
  {{- else }}
  featureCompatibilityVersion: {{ regexFind "\\d\\.\\d" .Values.mongoDBVersion | quote }}
  {{- end }}

  opsManager:
    configMapRef:
      name: project-{{ .Values.opsManager.projectName | lower }}
  credentials: {{ .Values.opsManager.omSecret }}
  persistent: true
  {{- /* Test for sharded cluster, this take precedence over replica set */ -}}
  {{- if $sharded }}
  type: ShardedCluster
  shardCount: {{ .Values.sharding.shardSrv.shards }}
  mongodsPerShardCount: {{ .Values.sharding.shardSrv.memberPerShard }}
  mongosCount: {{ .Values.sharding.mongos.count }}
  configServerCount: {{ .Values.sharding.configSrv.replicas }}
  shard:
    agent:
      startupOptions:
        {{- include "mongodb-deployment.agentStartupOptions" . | trim | nindent 8 }}
    additionalMongodConfig:
      {{- include "mongodb-deployment.additionalMongodConfig" . | trim | nindent 6 }}
  shardPodSpec:
    podTemplate:
      spec:
        {{- if (hasKey .Values "imagePullSecrets") }}
        imagePullSecrets:
          - name: {{ .Values.imagePullSecrets }}
        {{- end }}
        initContainers:
          - name: mongodb-kubernetes-init-database
        containers:
          - name: mongodb-enterprise-database
            resources:
              limits:
                cpu: {{ .Values.sharding.shardSrv.resources.limits.cpu }}
                memory: {{ .Values.sharding.shardSrv.resources.limits.mem }}
              requests:
                cpu: {{ .Values.sharding.shardSrv.resources.requests.cpu }}
                memory: {{ .Values.sharding.shardSrv.resources.requests.mem }}
      podAntiAffinityTopologyKey: "kubernetes.io/hostname"
    persistence:
      {{- if eq (.Values.sharding.shardSrv.storage.persistenceType | lower) "single"}}
      single:
        storage: {{ .Values.sharding.shardSrv.storage.single.size }}
        storageClass: {{ .Values.sharding.shardSrv.storage.single.storageClass }}
      {{- else }}
      multiple:
        data:
          storage: {{ .Values.sharding.shardSrv.storage.multi.data.size }}
          storageClass: {{ .Values.sharding.shardSrv.storage.multi.data.storageClass }}
        journal:
          storage: {{ .Values.sharding.shardSrv.storage.multi.journal.size }}
          storageClass: {{ .Values.sharding.shardSrv.storage.multi.journal.storageClass }}
        logs:
          storage: {{ .Values.sharding.shardSrv.storage.multi.logs.size }}
          storageClass: {{ .Values.sharding.shardSrv.storage.multi.logs.storageClass }}
      {{- end }}
  mongos:
    agent:
      startupOptions:
        {{- include "mongodb-deployment.agentStartupOptions" . | trim | nindent 8 }}
    additionalMongodConfig:
      {{- include "mongodb-deployment.additionalMongodConfig" . | trim | nindent 6 }}
  mongosPodSpec:
    podTemplate:
      spec:
        {{- if (hasKey .Values "imagePullSecrets") }}
        imagePullSecrets:
          - name: {{ .Values.imagePullSecrets }}
        {{- end }}
        initContainers:
          - name: mongodb-kubernetes-init-database
        containers:
          - name: mongodb-enterprise-database
            resources:
              limits:
                cpu: {{ .Values.sharding.mongos.resources.limits.cpu }}
                memory: {{ .Values.sharding.mongos.resources.limits.mem }}
              requests:
                cpu: {{ .Values.sharding.mongos.resources.requests.cpu }}
                memory: {{ .Values.sharding.mongos.resources.requests.mem }}
    podAntiAffinityTopologyKey: "kubernetes.io/hostname"
  configSrv:
    agent:
      startupOptions:
        {{- include "mongodb-deployment.agentStartupOptions" . | trim | nindent 8 }}
    additionalMongodConfig:
      {{- include "mongodb-deployment.additionalMongodConfig" . | trim | nindent 6 }}
  configSrvPodSpec:
    podTemplate:
      spec:
        {{- if (hasKey .Values "imagePullSecrets") }}
        imagePullSecrets:
          - name: {{ .Values.imagePullSecrets }}
        {{- end }}
        initContainers:
          - name: mongodb-kubernetes-init-database
        containers:
          - name: mongodb-enterprise-database
            resources:
              limits:
                cpu: {{ .Values.sharding.configSrv.resources.limits.cpu }}
                memory: {{ .Values.sharding.configSrv.resources.limits.mem }}
              requests:
                cpu: {{ .Values.sharding.configSrv.resources.requests.cpu }}
                memory: {{ .Values.sharding.configSrv.resources.requests.mem }}
      podAntiAffinityTopologyKey: "kubernetes.io/hostname"
    persistence:
      {{- if eq (.Values.sharding.configSrv.storage.persistenceType | lower) "single"}}
      single:
        storage: {{ .Values.sharding.configSrv.storage.single.size }}
        storageClass: {{ .Values.sharding.configSrv.storage.single.storageClass }}
      {{- else }}
      multiple:
        data:
          storage: {{ .Values.sharding.configSrv.storage.multi.data.size }}
          storageClass: {{ .Values.sharding.configSrv.storage.multi.data.storageClass }}
        journal:
          storage: {{ .Values.sharding.configSrv.storage.multi.journal.size }}
          storageClass: {{ .Values.sharding.configSrv.storage.multi.journal.storageClass }}
        logs:
          storage: {{ .Values.sharding.configSrv.storage.multi.logs.size }}
          storageClass: {{ .Values.sharding.configSrv.storage.multi.logs.storageClass }}
      {{- end }}
  {{- else }}
  type: ReplicaSet
  members: {{ .Values.replicaSet.replicas }}
  podSpec:
    podTemplate:
      spec:
        {{- if (hasKey .Values "imagePullSecrets") }}
        imagePullSecrets:
          - name: {{ .Values.imagePullSecrets }}
        {{- end }}
        initContainers:
          - name: mongodb-kubernetes-init-database
        containers:
          - name: mongodb-enterprise-database
            resources:
              limits:
                cpu: {{ .Values.replicaSet.resources.limits.cpu }}
                memory: {{ .Values.replicaSet.resources.limits.mem }}
              requests:
                cpu: {{ .Values.replicaSet.resources.requests.cpu }}
                memory: {{ .Values.replicaSet.resources.requests.mem }}
    podAntiAffinityTopologyKey: "kubernetes.io/hostname"
    persistence:
      {{- if eq (.Values.replicaSet.storage.persistenceType | lower) "single"}}
      single:
        storage: {{ .Values.replicaSet.storage.single.size }}
        storageClass: {{ .Values.replicaSet.storage.single.storageClass }}
      {{- else }}
      multiple:
        data:
          storage: {{ .Values.replicaSet.storage.multi.data.size }}
          storageClass: {{ .Values.replicaSet.storage.multi.data.storageClass }}
        journal:
          storage: {{ .Values.replicaSet.storage.multi.journal.size }}
          storageClass: {{ .Values.replicaSet.storage.multi.journal.storageClass }}
        logs:
          storage: {{ .Values.replicaSet.storage.multi.logs.size }}
          storageClass: {{ .Values.replicaSet.storage.multi.logs.storageClass }}
      {{- end }}
  additionalMongodConfig:
    {{- include "mongodb-deployment.additionalMongodConfig" . | trim | nindent 4 }}
  {{ if and (hasKey .Values.replicaSet "extAccess") (hasKey .Values.replicaSet.extAccess "enabled") (eq .Values.replicaSet.extAccess.enabled true) (eq .Values.tls.enabled true) -}}
  connectivity:
    replicaSetHorizons:
      {{- range .Values.replicaSet.extAccess.ports }}
      - "external": "{{ .horizonName }}:{{ .port }}"
      {{- end }}
  {{- end }}
  agent:
    startupOptions:
      {{- include "mongodb-deployment.agentStartupOptions" . | trim | nindent 6 }}
  {{- end }}
  {{- $ext := ternary ((.Values.sharding | default dict).extAccess | default dict) ((.Values.replicaSet | default dict).extAccess | default dict) $sharded }}
  {{- if eq ($ext.enabled | default false) true }}
  externalAccess:
    {{- include "mongodb-deployment.externalAccess" (dict "root" . "extAccess" $ext) | trim | nindent 4 }}
  {{- end }}
  security:
    authentication:
      enabled: true
      ignoreUnknownUsers: {{ ne (.Values.auth.allowNoManagedUsers | toString) "false" }}
      modes: 
      {{- if and (hasKey .Values.auth "scram") (hasKey .Values.auth.scram "enabled") (eq .Values.auth.scram.enabled true) }}
        - SCRAM
      {{- end }}
      {{- if and (hasKey .Values.auth "ldap") (hasKey .Values.auth.ldap "enabled") (eq .Values.auth.ldap.enabled true) }}
        - LDAP
      ldap:
        servers:
        {{- range .Values.auth.ldap.servers }}
          - {{ . }}
        {{- end }}
        transportSecurity: {{ if .Values.auth.ldap.ldaps }}tls{{ end }}
        {{- if .Values.auth.ldap.ldaps }}
        caConfigMapRef:
          name: {{ .Values.auth.ldap.caConfigMap }}
          key: ca-pem
        {{- end }}
        bindQueryUser: {{ .Values.auth.ldap.bindUserDN }}
        bindQueryPasswordSecretRef:
          name: {{ .Values.auth.ldap.bindUserSecret }}
        userToDNMapping: {{ .Values.auth.ldap.userToDNMapping | quote}}
        authzQueryTemplate: {{ .Values.auth.ldap.authzQueryTemplate | quote | default "" }}
      {{- end }}
    {{- if .Values.tls.enabled }}
      internalCluster: "X509"
      agents:
        mode: SCRAM
    certsSecretPrefix: "mdb"
    tls:
      ca: {{ .Values.tls.caConfigMap }}
      {{- with (include "mongodb-deployment.additionalCertificateDomains" . | fromYamlArray) }}
      additionalCertificateDomains:{{ . | toYaml | trim | nindent 8 }}
      {{- end }}
    {{- end }}
  {{- if hasKey .Values "backup" }}
  backup:
    mode: {{ .Values.backup.mode }}
    {{- if eq (.Values.backup.mode | lower) "enabled" }}
    {{- with .Values.backup.assignmentLabels }}
    assignmentLabels:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- if not $sharded }}
    autoTerminateOnDeletion: {{ .Values.backup.autoTerminateOnDeletion }}
    {{- end }}
    {{- if (((.Values.backup.encryption | default dict).kmip | default dict).enabled) }}
    encryption:
      kmip:
        client:
          clientCertificatePrefix: {{ .Values.backup.encryption.kmip.client.clientCertificatePrefix }}
    {{- end }}
    snapshotSchedule:
      snapshotIntervalHours: {{ .Values.backup.snapshotSchedule.snapshotIntervalHours }}
      snapshotRetentionDays: {{ .Values.backup.snapshotSchedule.snapshotRetentionDays }}
      dailySnapshotRetentionDays: {{ .Values.backup.snapshotSchedule.dailySnapshotRetentionDays }}
      weeklySnapshotRetentionWeeks: {{ .Values.backup.snapshotSchedule.weeklySnapshotRetentionWeeks }}
      monthlySnapshotRetentionMonths: {{ .Values.backup.snapshotSchedule.monthlySnapshotRetentionMonths }}
      pointInTimeWindowHours: {{ .Values.backup.snapshotSchedule.pointInTimeWindowHours }}
      referenceHourOfDay: {{ .Values.backup.snapshotSchedule.referenceHourOfDay }}
      referenceMinuteOfHour: {{ .Values.backup.snapshotSchedule.referenceMinuteOfHour }}
      fullIncrementalDayOfWeek: {{ .Values.backup.snapshotSchedule.fullIncrementalDayOfWeek }}
      {{- if $sharded }}
      clusterCheckpointIntervalMin: {{ .Values.backup.snapshotSchedule.clusterCheckpointIntervalMin }}
      {{- end }}
    {{- end }}
  {{- end }}
