
{{ if or (and (hasKey .Values.replicaSet "extAccess") (hasKey .Values.replicaSet.extAccess "enabled") (eq .Values.replicaSet.extAccess.enabled true) (eq .Values.tls.enabled true)) (and (hasKey .Values.sharding "extAccess") (hasKey .Values.sharding.extAccess "enabled") (eq .Values.sharding.extAccess.enabled true)) -}}
{{- $app := (.Values.clusterName | lower) -}}
{{- $namespace := .Release.Namespace -}}
{{- if and (hasKey .Values "sharding") (hasKey .Values.sharding "enabled") (eq .Values.sharding.enabled true) (hasKey .Values.sharding "extAccess") (hasKey .Values.sharding.extAccess "enabled") (eq .Values.sharding.extAccess.enabled true) (hasKey .Values.sharding.extAccess "ports")}}

{{- $exposeMethod := ternary "NodePort" "LoadBalancer" (eq (.Values.replicaSet.extAccess.exposeMethod | lower) "nodeport")}}
{{- range $index, $value := .Values.sharding.extAccess.ports }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $app }}-mongos-{{ $index }}-svc-external
  namespace: {{ $namespace }}
spec:
  clusterIP: ""
  externalTrafficPolicy: Cluster
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    {{- if eq ( $exposeMethod | lower) "nodeport" }}
    nodePort: {{ $value }}
    {{- end }}
  selector:
    statefulset.kubernetes.io/pod-name: {{ $app }}-mongos-{{$index}}
    controller: mongodb-enterprise-operator
  sessionAffinity: None
  type: NodePort
{{- end }}

{{- else if  and (hasKey .Values "replicaSet") (hasKey .Values.replicaSet "enabled") (eq .Values.replicaSet.enabled true) (hasKey .Values.replicaSet "extAccess") (hasKey .Values.replicaSet.extAccess "enabled") (eq .Values.replicaSet.extAccess.enabled true)}}
{{- $exposeMethod := ternary "NodePort" "LoadBalancer" (eq (.Values.replicaSet.extAccess.exposeMethod | lower) "nodeport")}}
{{- range $index, $value := .Values.replicaSet.extAccess.ports }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $app }}-{{$index}}-svc
  namespace: {{ $namespace }}
spec:
  {{- if (hasKey $value "clusterIP") }}
  clusterIP: {{ $value.clusterIP }}
  {{- else }}
  clusterIP: ""
  {{- end }}
  externalTrafficPolicy: Cluster
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    {{- if eq ( $exposeMethod | lower) "nodeport" }}
    nodePort: {{ $value.port }}
    {{- end }}
  selector:
    app: {{ $app }}-svc
    statefulset.kubernetes.io/pod-name: {{ $app }}-{{$index}}
  sessionAffinity: None
  type: {{ $exposeMethod }}

{{- end }}
{{- end }}
{{- end }}