apiVersion: v2
name: mongodb-deployment
version: "3.0.0"
appVersion: "1.11.0"
kubeVersion: ">=1.34.0-0"
home: https://github.com/beergeek
description: Deploy MongoDB Enterprise Replica Set or Sharded Cluster, securely, with MongoDB Controllers for Kubernetes (MCK).
maintainers:
  - name: beergeek
    email: brett.gray@mongodb.com
annotations:
  mongodb.com/mck-version: "1.11.0"
