---

clusterName: clown-cluster

mongoDBVersion: 5.0.13-ent


sharding:
  enabled: true
  shardSrv:
    shards: 2
    memberPerShard: 3
    resources:
      limits:
        cpu: 2
        mem: 2Gi
      requests:
        cpu: 1
        mem: 2Gi
    storage:
      nfs: false
      persistenceType: single
      single:
        size: 2Gi
        storageClass: data
      multi:
        data:
          size: 5Gi
          storageClass: dataClass
        journal:
          size: 5Gi
          storageClass: journalClass
        logs:
          size: 5Gi
          storageClass: logClass
  configSrv:
    replicas: 3
    resources:
      limits:
        cpu: 2
        mem: 2Gi
      requests:
        cpu: 1
        mem: 2Gi
    storage:
      nfs: false
      persistenceType: single
      single:
        size: 1Gi
        storageClass: data
      multi:
        data:
          size: 5Gi
          storageClass: dataClass
        journal:
          size: 5Gi
          storageClass: journalClass
        logs:
          size: 5Gi
          storageClass: logClass
  mongos:
    count: 2
    resources:
      limits:
        cpu: 2
        mem: 2Gi
      requests:
        cpu: 1
        mem: 2Gi
  extAccess:
    enabled: true
    externalDomains:
    - "mongodb.local"
    ports:
      - horizonName: "clown-cluster.mongodb.local"
        port: 31299
        clusterIP: 10.43.125.29


replicaSet:
  enabled: true
  replicas: 3
  resources:
    limits:
      cpu: 2
      mem: 4Gi
    requests:
      cpu: 1
      mem: 4Gi
  storage:
    nfs: false
    persistenceType: single
    single:
      size: 5Gi
      storageClass: data
    multi:
      data:
        size: 5Gi
        storageClass: dataClass
      journal:
        size: 5Gi
        storageClass: journalClass
      logs:
        size: 5Gi
        storageClass: logClass
  extAccess:
    enabled: true
    exposeMethod: NodePort
    ports:
      - horizonName: "rs-0-0.mongodb.local"
        port: 31250
        clusterIP: 10.43.125.20
      - horizonName: "rs-0-1.mongodb.local"
        port: 31251
        clusterIP: 10.43.125.21
      - horizonName: "rs-0-2.mongodb.local"
        port: 31252
        clusterIP: 10.43.125.22

agent:
  logLevel: DEBUG
  startupOptions:
    maxLogFiles: "30"

logLevel: DEBUG

auth:
  scram:
    enabled: true
  ldap:
    enabled: true
    servers:
      - ad0.mongodb.local
    ldaps: true
    caConfigMap: custom-ca
    bindUserDN: 'CN=ldap-bind-user,CN=Users,DC=mongodb,DC=local'
    bindUserSecret: binduserpasswd
    userToDNMapping: '[{ match: "(.+)@MONGODB.LOCAL", substitution: "cn={0},cn=Users,dc=mongodb,dc=local"}]'
    authzQueryTemplate: '{USER}?memberOf?base'

opsManager:
  tlsEnabled: true
  baseUrl: https://mongod0.mongodb.local:8443
  orgId: 5e439737e976cc5e50a7b13d
  projectName: K8S-CLOWNCLUSTER
  omSecret: organization-secret
  caConfigmap: om-ca-cert

tls:
  enabled: true
  caConfigMap: custom-ca

mongoDBAdminPasswdSecret: dev-adm-passwd

kmip:
  enabled: false
  host: kmip-svc.mongodb.svc.cluster.local
  port: 5696

additionalUsers:
  - username: om-user
    passwdSecret: om-user
    roles:
      - db: admin
        role: "clusterMonitor"
      - db: admin
        role: "readWriteAnyDatabase"
      - db: admin
        role: "userAdminAnyDatabase"
